services:
  server:
    image: r3dpnd/taskflow-server:latest
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    restart: unless-stopped

  client:
    image: r3dpnd/taskflow-client:latest
    ports:
      - "3000:80"
    env_file:
      - ./client/.env
    restart: unless-stopped